%YAML:1.0

use_gpu: 0
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
output_path: "/home/jonathan/datasets/vins_multi_output"

imu:
    num: 1
    topic: "/imu_apps"
    #imu parameters       The more accurate parameters you provide, the better performance
    acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2   0.04
    gyr_n: 0.05         # gyroscope measurement noise standard deviation.     #0.05  0.004
    acc_w: 0.01         # accelerometer bias random work noise standard deviation.  #0.002
    gyr_w: 0.004       # gyroscope bias random work noise standard deviation.     #4.0e-5
    g_norm: 9.80         # gravity magnitude

    center_T_imu: !!opencv-matrix
        rows: 4
        cols: 4
        dt: d
        data: [    1.0,    0.0,    0.0,   -2.0e-02,
                   0.0,    1.0,    0.0,    0.0e-02,
                   0.0,    0.0,    1.0,    1.0e-02,
                   0.0,    0.0,    0.0,    1.0 ]

cam_module:
    num: 4
    modules:
      - cam_id: 1 #tracking front fisheye / kannala brandt camera
        depth: 0
        stereo: 0
        image_width: 1280
        image_height: 800
        image0_topic: "/tracking_front"
        cam0_calib: "opencv_tracking_front_calib.yaml"
        td: 0.015                                #VOXL! change? # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
        rolling_shutter: 0                        # 0: global shutter camera, 1: rolling shutter camera
        rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

        imu_T_cam0: !!opencv-matrix  #VOXL! change this!
            rows: 4
            cols: 4
            dt: d
            data: [    0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0 ]         

      - cam_id: 2 #tracking down fisheye / kannala brandt camera
        depth: 0
        stereo: 0
        image_width: 1280
        image_height: 800
        image0_topic: "/tracking_down"
        cam0_calib: "opencv_tracking_down_calib.yaml"
        td: 0.015                                #VOXL! change? # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
        rolling_shutter: 0                        # 0: global shutter camera, 1: rolling shutter camera
        rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

        imu_T_cam0: !!opencv-matrix  #VOXL! change this!
            rows: 4
            cols: 4
            dt: d
            data: [    0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0 ]   

      - cam_id: 3 #thermal camera
        depth: 0
        stereo: 0
        image_width: 640
        image_height: 512
        image0_topic: "/ircam"
        cam0_calib: "opencv_ircam_calib.yaml"
        td: 0.015                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
        rolling_shutter: 1                      # 0: global shutter camera, 1: rolling shutter camera
        rolling_shutter_tr: 0.03333               # unit: s. rolling shutter read out time per frame (from data sheet). 

        imu_T_cam0: !!opencv-matrix
            rows: 4
            cols: 4
            dt: d
            data: [    0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0 ]

      - cam_id: 4 #low light camera
        depth: 0
        stereo: 0
        image_width: 2704
        image_height: 1540
        image0_topic: "/low_light_down"
        cam0_calib: "opencv_low_light_down_calib.yaml"
        td: 0.015                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
        rolling_shutter: 1                      # 0: global shutter camera, 1: rolling shutter camera
        rolling_shutter_tr: 0.03333               # unit: s. rolling shutter read out time per frame (from data sheet). 

        imu_T_cam0: !!opencv-matrix
            rows: 4
            cols: 4
            dt: d
            data: [    0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0,
                       0.0,    0.0,    0.0,    0.0 ]

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.


#Multiple thread support
multiple_thread: 0 #VOXL! Maybe check validity of setting multiple_thread to 1.

#feature traker paprameters
max_cnt: 250            # max feature number in feature tracking
min_dist: 40            # min distance between two features 
freq: 15                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
depth_min: 0.2
depth_max: 9.0
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           #VOXL! set to 1 only when testing on workstation # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy
equalize: 1             # if image is too dark or light, trun on equalize to find enough features

#optimization parameters
max_solver_time: 0.06  # max solver itration time (s), to guarantee real time
max_num_iterations: 12   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/jonathan/datasets/vins_multi_output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization purpose; you can close this function by setting 0 
