%YAML:1.0  #TODO: INSERT CORRECT PARAMETERS!
---
model_type: KANNALA_BRANDT
camera_name: "tracking_front"
image_width: 1280
image_height: 800
distortion_parameters:
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
projection_parameters:
  fx: 0.0
  fy: 0.0
  cx: 0.0
  cy: 0.0
